# Generated by Django 2.1 on 2018-08-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehengas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lehenga_price', models.IntegerField()),
                ('lehenga_desc', models.CharField(max_length=500)),
                ('lehenga_size', models.CharField(max_length=10)),
                ('lehenga_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='weddingLehenga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedL_colour', models.CharField(max_length=50)),
                ('lehenga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.Lehengas')),
            ],
        ),
    ]
