# Generated by Django 2.1 on 2018-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0003_remove_lehengas_lehenga_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehengas',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lehengas',
            name='lehenga_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lehengas',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
